### ISSUE TITLE
Readthedocs build is failing

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#277]
## What happened
I've noticed the Readthedocs build is failing on the CI checks for PR 237.

* Here's a link to a recent failing build: ttps://readthedocs.org/projects/dask-image/builds/19108499/
* The error message says "We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently."
* And the python traceback error "ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/jinja2/__init__.py)"

<details>
<summary>Expand for build failure details:</summary>

```

ttps://readthedocs.org/projects/dask-image/builds/19108499/
Build #19108499
Pull Request #237 (431de07f34d2391c957bd01a94df9863f1bb7699) 

Build failed

Error
We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/sphinx/__main__.py", line 13, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/sphinx/application.py", line 42, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, rst, progress_message, status_iterator
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/sphinx/util/rst.py", line 22, in <module>
    from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/dask-image/conda/237/lib/python3.7/site-packages/jinja2/__init__.py)

```

</details>

## Hypothesis

I found [this issue](https://github.com/sphinx-doc/sphinx/issues/10291) describing the same problem, which people have resolved by pinning Jinja (eg: [this comment](https://github.com/sphinx-doc/sphinx/issues/10291#issuecomment-1078046986))

> Pinning to `Jinja2<3.1` fixed it for our project.

I think we should also try pinning to `Jinja2<3.1` and see if that fixes things.

Extra note: 
In October 2022, the docs refresh PR https://github.com/dask/dask-image/pull/273 updated the pinning from Jinja2<3.1` to [the current `jinja2==3.1.2`](https://github.com/dask/dask-image/blob/9e3bfead7e4338755373786061a119f4f409d951/continuous_integration/environment-doc.yml#L11). Everything seemed to work well together then, which might suggest my hypothesis is wrong and it isn't the Jinja version that's the trouble. Nevertheless, it's a quick (I hope) thing to check, and I don't have any better ideas right now.

**Comment by GenevieveBuckley** [comment]
I think https://github.com/dask/dask-image/pull/278 worked, closing this issue
