### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by m-albert** [dask/dask-image#352]
Probably we should create a release given the new functionality from https://github.com/dask/dask-image/pull/213 and https://github.com/dask/dask-image/pull/344 !

Happy to do this in the next days if you guys agree @jakirkham @GenevieveBuckley.

**Comment by jakirkham** [comment]
Would suggest we include PR: https://github.com/dask/dask-image/pull/354

That way users can see the new features added in the docs associated with the new version

Otherwise +1 on releasing. Thanks for handling this Marvin! 🙏

**Comment by jakirkham** [comment]
Think we should be good to go

**Comment by GenevieveBuckley** [comment]
Absolutely!

**Comment by m-albert** [comment]
Great :) Unless one of you guys would do it earlier, I'd plan to do it on Monday.

**Comment by ericpre** [comment]
xref https://github.com/conda-forge/dask-image-feedstock/pull/20, the current release doesn't build on conda-forge:

```

2024-03-10T13:47:56.5768709Z Processing $SRC_DIR
2024-03-10T13:47:56.5828345Z   Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-1mw32res'
2024-03-10T13:47:56.5829325Z   Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
2024-03-10T13:47:56.5829744Z   Created temporary directory: /tmp/pip-pip-egg-info-4o8laagz
2024-03-10T13:47:56.5829985Z   Preparing metadata (setup.py): started
2024-03-10T13:47:56.5830218Z   Running command python setup.py egg_info
2024-03-10T13:47:56.7345781Z   /home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/versioneer.py:420: SyntaxWarning: invalid escape sequence '\s'
2024-03-10T13:47:56.7356532Z     LONG_VERSION_PY['git'] = '''
2024-03-10T13:47:56.7449342Z   Traceback (most recent call last):
2024-03-10T13:47:56.7461702Z     File "<string>", line 2, in <module>
2024-03-10T13:47:56.7471938Z     File "<pip-setuptools-caller>", line 34, in <module>
2024-03-10T13:47:56.7483120Z     File "/home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/setup.py", line 56, in <module>
2024-03-10T13:47:56.7493465Z       version=versioneer.get_version(),
2024-03-10T13:47:56.7503054Z               ^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7513336Z     File "/home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/versioneer.py", line 1479, in get_version
2024-03-10T13:47:56.7523768Z       return get_versions()["version"]
2024-03-10T13:47:56.7533222Z              ^^^^^^^^^^^^^^
2024-03-10T13:47:56.7546946Z     File "/home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/versioneer.py", line 1411, in get_versions
2024-03-10T13:47:56.7556852Z       cfg = get_config_from_root(root)
2024-03-10T13:47:56.7565043Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7573901Z     File "/home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/versioneer.py", line 341, in get_config_from_root
2024-03-10T13:47:56.7581732Z       parser = configparser.SafeConfigParser()
2024-03-10T13:47:56.7589781Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7598578Z   AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
2024-03-10T13:47:56.7801463Z   error: subprocess-exited-with-error
2024-03-10T13:47:56.7802006Z   
2024-03-10T13:47:56.7802316Z   × python setup.py egg_info did not run successfully.
2024-03-10T13:47:56.7804977Z   │ exit code: 1
2024-03-10T13:47:56.7805501Z   ╰─> See above for output.
2024-03-10T13:47:56.7805688Z   
2024-03-10T13:47:56.7806906Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2024-03-10T13:47:56.7826572Z   full command: /home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -c '
2024-03-10T13:47:56.7827453Z   exec(compile('"'"''"'"''"'"'
2024-03-10T13:47:56.7827836Z   # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
2024-03-10T13:47:56.7828699Z   #
2024-03-10T13:47:56.7829068Z   # - It imports setuptools before invoking setup.py, to enable projects that directly
2024-03-10T13:47:56.7829405Z   #   import from `distutils.core` to work with newer packaging standards.
2024-03-10T13:47:56.7829780Z   # - It provides a clear error message when setuptools is not installed.
2024-03-10T13:47:56.7830159Z   # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
2024-03-10T13:47:56.7830537Z   #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
2024-03-10T13:47:56.7830897Z   #     manifest_maker: standard file '"'"'-c'"'"' not found".
2024-03-10T13:47:56.7831247Z   # - It generates a shim setup.py, for handling setup.cfg-only projects.
2024-03-10T13:47:56.7831483Z   import os, sys, tokenize
2024-03-10T13:47:56.7831673Z   
2024-03-10T13:47:56.7831832Z   try:
2024-03-10T13:47:56.7832021Z       import setuptools
2024-03-10T13:47:56.7832220Z   except ImportError as error:
2024-03-10T13:47:56.7832417Z       print(
2024-03-10T13:47:56.7832757Z           "ERROR: Can not execute `setup.py` since setuptools is not available in "
2024-03-10T13:47:56.7833004Z           "the build environment.",
2024-03-10T13:47:56.7833197Z           file=sys.stderr,
2024-03-10T13:47:56.7833384Z       )
2024-03-10T13:47:56.7833552Z       sys.exit(1)
2024-03-10T13:47:56.7833743Z   
2024-03-10T13:47:56.7833909Z   __file__ = %r
2024-03-10T13:47:56.7834108Z   sys.argv[0] = __file__
2024-03-10T13:47:56.7834281Z   
2024-03-10T13:47:56.7834479Z   if os.path.exists(__file__):
2024-03-10T13:47:56.7834687Z       filename = __file__
2024-03-10T13:47:56.7834886Z       with tokenize.open(__file__) as f:
2024-03-10T13:47:56.7835106Z           setup_py_code = f.read()
2024-03-10T13:47:56.7835287Z   else:
2024-03-10T13:47:56.7835567Z       filename = "<auto-generated setuptools caller>"
2024-03-10T13:47:56.7835809Z       setup_py_code = "from setuptools import setup; setup()"
2024-03-10T13:47:56.7836019Z   
2024-03-10T13:47:56.7836210Z   exec(compile(setup_py_code, filename, "exec"))
2024-03-10T13:47:56.7836768Z   '"'"''"'"''"'"' % ('"'"'/home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-4o8laagz
2024-03-10T13:47:56.7837251Z   cwd: /home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/
2024-03-10T13:47:56.7893193Z   Preparing metadata (setup.py): finished with status 'error'
2024-03-10T13:47:56.7893855Z error: metadata-generation-failed
2024-03-10T13:47:56.7894451Z 
2024-03-10T13:47:56.7894955Z × Encountered error while generating package metadata.
2024-03-10T13:47:56.7895316Z ╰─> See above for output.
2024-03-10T13:47:56.7896261Z 
2024-03-10T13:47:56.7896621Z note: This is an issue with the package mentioned above, not pip.
2024-03-10T13:47:56.7896917Z hint: See above for details.
2024-03-10T13:47:56.7916412Z Exception information:
2024-03-10T13:47:56.7916986Z Traceback (most recent call last):
2024-03-10T13:47:56.7917595Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 64, in generate_metadata
2024-03-10T13:47:56.7917982Z     call_subprocess(
2024-03-10T13:47:56.7918418Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
2024-03-10T13:47:56.7918737Z     raise error
2024-03-10T13:47:56.7919038Z pip._internal.exceptions.InstallationSubprocessError: python setup.py egg_info exited with 1
2024-03-10T13:47:56.7919253Z 
2024-03-10T13:47:56.7919580Z The above exception was the direct cause of the following exception:
2024-03-10T13:47:56.7920056Z 
2024-03-10T13:47:56.7920352Z Traceback (most recent call last):
2024-03-10T13:47:56.7921002Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2024-03-10T13:47:56.7921397Z     status = run_func(*args)
2024-03-10T13:47:56.7921640Z              ^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7922241Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
2024-03-10T13:47:56.7922570Z     return func(self, options, args)
2024-03-10T13:47:56.7922813Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7923196Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
2024-03-10T13:47:56.7923517Z     requirement_set = resolver.resolve(
2024-03-10T13:47:56.7923749Z                       ^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7924173Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
2024-03-10T13:47:56.7924517Z     collected = self.factory.collect_root_requirements(root_reqs)
2024-03-10T13:47:56.7924789Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7925242Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
2024-03-10T13:47:56.7925561Z     reqs = list(
2024-03-10T13:47:56.7925786Z            ^^^^^
2024-03-10T13:47:56.7926386Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
2024-03-10T13:47:56.7926762Z     cand = self._make_base_candidate_from_link(
2024-03-10T13:47:56.7927000Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7927464Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
2024-03-10T13:47:56.7927828Z     self._link_candidate_cache[link] = LinkCandidate(
2024-03-10T13:47:56.7928073Z                                        ^^^^^^^^^^^^^^
2024-03-10T13:47:56.7928504Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
2024-03-10T13:47:56.7928817Z     super().__init__(
2024-03-10T13:47:56.7929261Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2024-03-10T13:47:56.7929597Z     self.dist = self._prepare()
2024-03-10T13:47:56.7929821Z                 ^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7930250Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
2024-03-10T13:47:56.7930574Z     dist = self._prepare_distribution()
2024-03-10T13:47:56.7930819Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7931256Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
2024-03-10T13:47:56.7931641Z     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
2024-03-10T13:47:56.7931924Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7932347Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
2024-03-10T13:47:56.7932715Z     return self._prepare_linked_requirement(req, parallel_builds)
2024-03-10T13:47:56.7932972Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7933411Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
2024-03-10T13:47:56.7933767Z     dist = _get_prepared_distribution(
2024-03-10T13:47:56.7933997Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7934430Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
2024-03-10T13:47:56.7934762Z     abstract_dist.prepare_distribution_metadata(
2024-03-10T13:47:56.7935238Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
2024-03-10T13:47:56.7935560Z     self.req.prepare_metadata()
2024-03-10T13:47:56.7935994Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 585, in prepare_metadata
2024-03-10T13:47:56.7936429Z     self.metadata_directory = generate_metadata_legacy(
2024-03-10T13:47:56.7936688Z                               ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10T13:47:56.7937136Z   File "$PREFIX/lib/python3.12/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
2024-03-10T13:47:56.7937490Z     raise MetadataGenerationFailed(package_details=details) from error
2024-03-10T13:47:56.7937820Z pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
2024-03-10T13:47:56.7938242Z Removed file://$SRC_DIR from build tracker '/tmp/pip-build-tracker-1mw32res'
2024-03-10T13:47:56.7938627Z Removed build tracker: '/tmp/pip-build-tracker-1mw32res'
2024-03-10T13:47:57.4655872Z 
2024-03-10T13:47:57.4668520Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2024-03-10T13:47:57.4669266Z 
2024-03-10T13:47:57.4671294Z     Traceback (most recent call last):
2024-03-10T13:47:57.4672277Z       File "/opt/conda/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
2024-03-10T13:47:57.4673444Z         return func(*args, **kwargs)
2024-03-10T13:47:57.4675504Z       File "/opt/conda/lib/python3.10/site-packages/conda/cli/main.py", line 83, in main_subshell
2024-03-10T13:47:57.4676719Z         exit_code = do_call(args, parser)
2024-03-10T13:47:57.4677500Z       File "/opt/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 172, in do_call
2024-03-10T13:47:57.4677964Z         result = plugin_subcommand.action(getattr(args, "_args", args))
2024-03-10T13:47:57.4678511Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/plugin.py", line 14, in build
2024-03-10T13:47:57.4678906Z         return execute(args)
2024-03-10T13:47:57.4679451Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 581, in execute
2024-03-10T13:47:57.4679840Z         api.build(
2024-03-10T13:47:57.4680333Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 255, in build
2024-03-10T13:47:57.4680719Z         return build_tree(
2024-03-10T13:47:57.4681228Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3782, in build_tree
2024-03-10T13:47:57.4681619Z         packages_from_this = build(
2024-03-10T13:47:57.4682132Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2654, in build
2024-03-10T13:47:57.4682508Z         utils.check_call_env(
2024-03-10T13:47:57.4683001Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 406, in check_call_env
2024-03-10T13:47:57.4683452Z         return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2024-03-10T13:47:57.4684580Z       File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 382, in _func_defaulting_env_to_os_environ
2024-03-10T13:47:57.4685538Z         raise subprocess.CalledProcessError(proc.returncode, _args)
2024-03-10T13:47:57.4686362Z     subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/dask-image_1710078359865/work/conda_build.sh']' returned non-zero exit status 1.
2024-03-10T13:47:57.4686798Z 
2024-03-10T13:47:57.4688515Z `$ /opt/conda/bin/conda build /home/conda/recipe_root -m /home/conda/feedstock_root/.ci_support/linux_64_.yaml --suppress-variables --clobber-file /home/conda/feedstock_root/.ci_support/clobber_linux_64_.yaml --extra-meta flow_run_id=azure_20240310.2.1 remote_url=*** sha=34d3d96072110f827417feae618445219c21e348`
2024-03-10T13:47:57.4689169Z 
2024-03-10T13:47:57.4689494Z   environment variables:
2024-03-10T13:47:57.4689847Z                  CIO_TEST=<not set>
2024-03-10T13:47:57.4690194Z     CONDA_ALLOW_SOFTLINKS=false
2024-03-10T13:47:57.4690554Z            CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
2024-03-10T13:47:57.4690927Z         CONDA_DEFAULT_ENV=base
2024-03-10T13:47:57.4691259Z                 CONDA_EXE=/opt/conda/bin/conda
2024-03-10T13:47:57.4692765Z CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1
2024-03-10T13:47:57.4693262Z              CONDA_PREFIX=/opt/conda
2024-03-10T13:47:57.4693611Z     CONDA_PROMPT_MODIFIER=(base)
2024-03-10T13:47:57.4693982Z          CONDA_PYTHON_EXE=/opt/conda/bin/python
2024-03-10T13:47:57.4694319Z                CONDA_ROOT=/opt/conda
2024-03-10T13:47:57.4696830Z               CONDA_SHLVL=1
2024-03-10T13:47:57.4697991Z            CURL_CA_BUNDLE=<not set>
2024-03-10T13:47:57.4698410Z                LD_PRELOAD=<not set>
2024-03-10T13:47:57.4698800Z                      PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr
2024-03-10T13:47:57.4699175Z                           /sbin:/usr/bin:/sbin:/bin:/home/conda/bin
2024-03-10T13:47:57.4699786Z          PYTHONUNBUFFERED=1
2024-03-10T13:47:57.4700214Z        REQUESTS_CA_BUNDLE=<not set>
2024-03-10T13:47:57.4700556Z             SSL_CERT_FILE=<not set>
2024-03-10T13:47:57.4700795Z 
2024-03-10T13:47:57.4701096Z      active environment : base
2024-03-10T13:47:57.4701441Z     active env location : /opt/conda
2024-03-10T13:47:57.4701775Z             shell level : 1
2024-03-10T13:47:57.4702321Z        user config file : /home/conda/.condarc
2024-03-10T13:47:57.4702683Z  populated config files : /opt/conda/.condarc
2024-03-10T13:47:57.4703047Z                           /home/conda/.condarc
2024-03-10T13:47:57.4703401Z           conda version : 24.1.2
2024-03-10T13:47:57.4703858Z     conda-build version : 24.1.2
2024-03-10T13:47:57.4704219Z          python version : 3.10.13.final.0
2024-03-10T13:47:57.4704553Z                  solver : libmamba (default)
2024-03-10T13:47:57.4705541Z        virtual packages : __archspec=1=x86_64_v4
2024-03-10T13:47:57.4706482Z                           __conda=24.1.2=0
2024-03-10T13:47:57.4706896Z                           __glibc=2.17=0
2024-03-10T13:47:57.4707256Z                           __linux=6.5.0=0
2024-03-10T13:47:57.4708129Z                           __unix=0=0
2024-03-10T13:47:57.4708469Z        base environment : /opt/conda  (writable)
2024-03-10T13:47:57.4708827Z       conda av data dir : /opt/conda/etc/conda
2024-03-10T13:47:57.4709185Z   conda av metadata url : None
2024-03-10T13:47:57.4709789Z            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
2024-03-10T13:47:57.4710290Z                           https://conda.anaconda.org/conda-forge/noarch
2024-03-10T13:47:57.4710682Z           package cache : /home/conda/feedstock_root/build_artifacts/pkg_cache
2024-03-10T13:47:57.4711064Z                           /opt/conda/pkgs
2024-03-10T13:47:57.4711410Z        envs directories : /opt/conda/envs
2024-03-10T13:47:57.4711738Z                           /home/conda/.conda/envs
2024-03-10T13:47:57.4712078Z                platform : linux-64
2024-03-10T13:47:57.4712805Z              user-agent : conda/24.1.2 requests/2.31.0 CPython/3.10.13 Linux/6.5.0-1015-azure centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.7
2024-03-10T13:47:57.4713309Z                 UID:GID : 1001:1001
2024-03-10T13:47:57.4717231Z              netrc file : None
2024-03-10T13:47:57.4717793Z            offline mode : False
2024-03-10T13:47:57.4718089Z 
2024-03-10T13:47:57.4718329Z 
2024-03-10T13:47:57.4718695Z An unexpected error has occurred. Conda has prepared the above report.
2024-03-10T13:47:57.4719089Z If you suspect this error is being caused by a malfunctioning plugin,
2024-03-10T13:47:57.4719621Z consider using the --no-plugins option to turn off plugins.
2024-03-10T13:47:57.4719906Z 
2024-03-10T13:47:57.4720313Z Example: conda --no-plugins install <package>
2024-03-10T13:47:57.4720579Z 
2024-03-10T13:47:57.4720943Z Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
2024-03-10T13:47:57.4721373Z the command line to run the command without plugins enabled.
2024-03-10T13:47:57.4721641Z 
2024-03-10T13:47:57.4721986Z Example: CONDA_NO_PLUGINS=true conda install <package>
2024-03-10T13:47:57.4722250Z 
2024-03-10T13:48:04.0606390Z 
2024-03-10T13:48:04.0674309Z ##[error]Bash exited with code '1'.
2024-03-10T13:48:04.0712724Z ##[section]Finishing: Run docker build

```

**Comment by m-albert** [comment]
Thanks @ericpre 🙏

**Comment by GenevieveBuckley** [comment]
> xref https://github.com/conda-forge/dask-image-feedstock/pull/20, the current release doesn't build on conda-forge:

I think we're ok to move forward. That build failed because of versioneer, and we have removed versioneer in the latest dask-image release (it's been replaced by setuptools-scm). The new v2024.5.0 conda-forge build https://github.com/conda-forge/dask-image-feedstock/pull/22 is successful, so I think we can go ahead and use that.

https://github.com/conda-forge/dask-image-feedstock/pull/20#issuecomment-2116888534
> This build looks like it's failing because of something to do with versioneer. Because we've removed versioneer and replaced it with setuptools-scm in the latest release (dask-image v2024.5.0), I think we should close this PR and move forward with #22 (which does build correctly).

**Comment by GenevieveBuckley** [comment]
I've merged https://github.com/conda-forge/dask-image-feedstock/pull/22 now.

dask-image v2024.5.0 should now be available from PyPI and conda-forge. Please try it out, and let us know if anything isn't working properly.
